apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hospital.local
    http:
      paths:
      - path: /v1/patients
        pathType: Prefix
        backend:
          service:
            name: patient-service
            port:
              number: 8001
      - path: /v1/doctors
        pathType: Prefix
        backend:
          service:
            name: doctor-service
            port:
              number: 8002
      - path: /v1/appointments
        pathType: Prefix
        backend:
          service:
            name: appointment-service
            port:
              number: 8003
      - path: /v1/bills
        pathType: Prefix
        backend:
          service:
            name: billing-service
            port:
              number: 8004
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80



